import type { BandProfile } from "./types";

export const bandProfiles: BandProfile[] = [
  { id: "160m", label: "160 m", frequencyMHz: 1.9, frequencyRange: "1810–2000 kHz", normalLayer: "F2", localNearRadiusKm: 120, nvisCandidate: true, notes: "Low band. Often heavy D-layer absorption in daytime.", fairReliability: { day: "very_low", twilight: "medium", night: "high" }, maxReturnElevationFairDeg: { day: 45, twilight: 75, night: 85 } },
  { id: "80m", label: "80 m", frequencyMHz: 3.65, frequencyRange: "3500–3800 kHz", normalLayer: "F2", localNearRadiusKm: 90, nvisCandidate: true, notes: "Regional/NVIS plus night-time longer propagation.", fairReliability: { day: "low", twilight: "high", night: "high" }, maxReturnElevationFairDeg: { day: 60, twilight: 85, night: 85 } },
  { id: "60m", label: "60 m", frequencyMHz: 5.36, frequencyRange: "5351.5–5366.5 kHz", normalLayer: "F2", localNearRadiusKm: 70, nvisCandidate: true, notes: "Often useful for short to regional HF.", fairReliability: { day: "medium", twilight: "high", night: "medium" }, maxReturnElevationFairDeg: { day: 85, twilight: 85, night: 65 } },
  { id: "40m", label: "40 m", frequencyMHz: 7.1, frequencyRange: "7000–7200 kHz", normalLayer: "F2", localNearRadiusKm: 60, nvisCandidate: true, notes: "Regional to Europe, but also longer skip depending on time.", fairReliability: { day: "high", twilight: "high", night: "medium" }, maxReturnElevationFairDeg: { day: 85, twilight: 75, night: 50 } },
  { id: "30m", label: "30 m", frequencyMHz: 10.125, frequencyRange: "10100–10150 kHz", normalLayer: "F2", localNearRadiusKm: 45, nvisCandidate: false, notes: "Often good for longer regional and DX.", fairReliability: { day: "medium", twilight: "high", night: "medium" }, maxReturnElevationFairDeg: { day: 70, twilight: 60, night: 35 } },
  { id: "20m", label: "20 m", frequencyMHz: 14.2, frequencyRange: "14000–14350 kHz", normalLayer: "F2", localNearRadiusKm: 35, nvisCandidate: false, notes: "Classic DX band.", fairReliability: { day: "high", twilight: "high", night: "medium" }, maxReturnElevationFairDeg: { day: 55, twilight: 50, night: 25 } },
  { id: "17m", label: "17 m", frequencyMHz: 18.1, frequencyRange: "18068–18168 kHz", normalLayer: "F2", localNearRadiusKm: 30, nvisCandidate: false, notes: "DX band, often needs better MUF than 20m.", fairReliability: { day: "medium", twilight: "high", night: "low" }, maxReturnElevationFairDeg: { day: 45, twilight: 45, night: 18 } },
  { id: "15m", label: "15 m", frequencyMHz: 21.2, frequencyRange: "21000–21450 kHz", normalLayer: "F2", localNearRadiusKm: 25, nvisCandidate: false, notes: "Higher HF band, usually day/twilight.", fairReliability: { day: "medium", twilight: "medium", night: "low" }, maxReturnElevationFairDeg: { day: 35, twilight: 30, night: 12 } },
  { id: "12m", label: "12 m", frequencyMHz: 24.94, frequencyRange: "24890–24990 kHz", normalLayer: "F2", localNearRadiusKm: 20, nvisCandidate: false, notes: "High HF, more condition dependent.", fairReliability: { day: "low", twilight: "medium", night: "very_low" }, maxReturnElevationFairDeg: { day: 25, twilight: 22, night: 8 } },
  { id: "10m", label: "10 m", frequencyMHz: 28.5, frequencyRange: "28000–29700 kHz", normalLayer: "F2", localNearRadiusKm: 20, nvisCandidate: false, notes: "Highly condition dependent.", fairReliability: { day: "low", twilight: "low", night: "very_low" }, maxReturnElevationFairDeg: { day: 18, twilight: 15, night: 5 } },
  { id: "6m", label: "6 m", frequencyMHz: 50.2, frequencyRange: "50–52 MHz", normalLayer: "Es", localNearRadiusKm: 15, nvisCandidate: false, notes: "Special case. Often tied to sporadic E.", fairReliability: { day: "low", twilight: "very_low", night: "very_low" }, maxReturnElevationFairDeg: { day: 15, twilight: 12, night: 8 } }
];
